// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE4TaWUY3uBMFmN1GJY0DVTtMuOgfPRqA',
    appId: '1:776712200018:web:af6bd1bc7704037037a48b',
    messagingSenderId: '776712200018',
    projectId: 'MuslimMind-fcb93',
    authDomain: 'MuslimMind-fcb93.firebaseapp.com',
    storageBucket: 'MuslimMind-fcb93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0nndcDQVpxBDJ6HPrzGBp2DqpjsoqEmw',
    appId: '1:776712200018:android:a12f1e2a94c68b7537a48b',
    messagingSenderId: '776712200018',
    projectId: 'MuslimMind-fcb93',
    storageBucket: 'MuslimMind-fcb93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC3rWAtJKNYUgGA-X_7pBOWucZG_C6xps',
    appId: '1:776712200018:ios:2a97e65761c9bebe37a48b',
    messagingSenderId: '776712200018',
    projectId: 'MuslimMind-fcb93',
    storageBucket: 'MuslimMind-fcb93.firebasestorage.app',
    iosBundleId: 'com.example.MuslimMindDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC3rWAtJKNYUgGA-X_7pBOWucZG_C6xps',
    appId: '1:776712200018:ios:2a97e65761c9bebe37a48b',
    messagingSenderId: '776712200018',
    projectId: 'MuslimMind-fcb93',
    storageBucket: 'MuslimMind-fcb93.firebasestorage.app',
    iosBundleId: 'com.example.MuslimMindDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE4TaWUY3uBMFmN1GJY0DVTtMuOgfPRqA',
    appId: '1:776712200018:web:004ccd689a0b337337a48b',
    messagingSenderId: '776712200018',
    projectId: 'MuslimMind-fcb93',
    authDomain: 'MuslimMind-fcb93.firebaseapp.com',
    storageBucket: 'MuslimMind-fcb93.firebasestorage.app',
  );
}
